import type { Metadata } from "next";
import { Inter, Poppins, Righteous } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Preloader } from "./components/Preloader";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});
const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

const righteous = Righteous({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-righteous",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} ${righteous.variable}`}
      >
        <Navbar />
        <Preloader />
        {children}
      </body>
    </html>
  );
}
